#!/bin/bash
#PBS -q MCSR
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=26
#PBS -l mem=256G
#PBS -N step_003
#PBS -e /ddn/home2/r2884/VDJ_TCR/xpbsout/step_003_flash/step_003_flash_error.txt
#PBS -o /ddn/home2/r2884/VDJ_TCR/xpbsout/step_003_flash/step_003_flash_output.txt

#submitted job like this
#mkdir -p /ddn/home2/r2884/VDJ_TCR/xpbsout/step_003_flash
#cd <project_dir>/<gitrepo>
#qsub step_003_flash.pbs

#Variables to set:
PRODIR=/ddn/home2/r2884/VDJ_TCR
STEP=step_003_flash

#running the script
mkdir -p ${PRODIR}/analysis/${STEP}
cd ${PRODIR}/apps/flash_v1.2.11/FLASH-1.2.11
./flash ${PRODIR}/analysis/step_002_trimmomatic/SRR392744Fp.fastq.gz ${PRODIR}/analysis/step_002_trimmomatic/SRR392744Rp.fastq.gz -M 90 -d /ddn/home2/r2884/VDJ_TCR/analysis/step_003_flash/
