#!/bin/bash
#PBS -q workq
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=6
#PBS -l mem=24G
#PBS -N step_003_flash_assemble
#PBS -e /ddn/home2/r2884/VDJ_TCR/xpbsout/step_003_flash_assemble/step_003_flash_assemble_error.txt
#PBS -o /ddn/home2/r2884/VDJ_TCR/xpbsout/step_003_flash_assemble/step_003_flash_assemble_output.txt

#submitted job like this
#mkdir -p /ddn/home2/r2884/VDJ_TCR/xpbsout/step_003_flash_assemble
#cd <project_dir>/<gitrepo>
#qsub step_003_flash_assemble.pbs

#Variables to set:
PRODIR=/ddn/home2/r2884/VDJ_TCR
STEP=step_003_flash_assemble

#running the script
mkdir -p ${PRODIR}/analysis/${STEP}
cd ${PRODIR}/apps/flash_v1.2.11/FLASH-1.2.11/flash
./flash ${PRODIR}/analysis/step_001_fastq-dump/SRR392744_1.fastq.gz ${PRODIR}/analysis/step_001_fastq-dump/SRR392744_2.fastq.gz -r 100 -d ${PRODIR}/analysis/step_003_flash/ 2>&1 | tee flash.log
