#!/bin/bash
#PBS -q workq
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=6
#PBS -l mem=24G
#PBS -N step_001_fast-dump_SRR
#PBS -e /ddn/home2/r2884/VDJ_TCR/xpbsout/step_001_fastq-dump/step_001_fastq-dump_error.txt
#PBS -o /ddn/home2/r2884/VDJ_TCR/xpbsout/step_001_fasq-dump/step_001_fastq-dump_output.txt

#submitted job like this
#mkdir -p /ddn/home2/r2884/VDJ_TCR/xpbsout/step_001_fastq-dump
#cd <project_dir>/<gitrepo>
#qsub step_001_fastq-dump.pbs

#Variables to set:
PRODIR=/ddn/home2/r2884/VDJ_TCR
STEP=step_001_fastq-dump

#running the script
mkdir -p ${PRODIR}/analysis/${STEP}
cd ${PROJDIR}/analysis/${STEP}

#fastq-dump.${version-2.10.8} ${PRODIR}/data/srr/SRR392744 --split-files --gzip
fastq-dump ${PRODIR}/data/srr/SRR392744 --split-files --gzip
